describe('投稿', () => {
  it("つぶやき", () => {
    cy.login("user", "MattarLiDev@1234")
    cy.visit('/')
    cy.get('textarea').type("This post is generated by Cypress")
    cy.get('[id="post"]').click()
    cy.wait(2000)
    cy.get('[id="msg"]').first().should('have.text', 'This post is generated by Cypress')
  })
})