describe('プロフィールを更新', () => {
  it("モーダルを開く", () => {
    cy.login("user", "MattarLiDev@1234")
    cy.visit('/user')
    cy.get('button[id="edit"]').click()
    cy.get('[id="name"]').clear()
    cy.get('[id="name"]').type("nmUser")
    cy.get('[id="avatar"]').attachFile('mattar.png');
    cy.get('[id="description"]').clear()
    cy.get('[id="description"]').type("Generated by Cypress");
    cy.get('[id="location"]').clear()
    cy.get('[id="location"]').type("日本");
    cy.get('[id="website"]').clear()
    cy.get('[id="website"]').type("https://cypress.io");
    cy.get('[id="update"]').click()
    cy.wait(5000)
  })
})

describe('更新', () => {
  it('確認', () => {
    cy.visit('/user')
    cy.get('h1').should('have.text', 'nmUser')
  })
})